version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
admin_secret: "secretHasuraPassword"
insecure_skip_tls_verify: true
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
